build: support Ubuntu 24.04 only, drop older Ubuntu versions
  Simplify the build helper script:

    - collapse the rhel/rocky 9.x cases into globs
    - drop unused helpers: version_le/lt/ge/gt, clean_kernel,
      test_install_package, and the unused color variables
    - replace the deprecated egrep with grep -E
    - group the helpers into logical sections
    - Add support for rocky 9.7 and 9.8

Assisted-by: Claude: Opus-5
Signed-off-by: Shubhika Garg <shubhika.garg@openairinterface.org>

diff --git a/installation/build_helper b/installation/build_helper
--- a/installation/build_helper
+++ b/installation/build_helper
@@ -1,55 +1,29 @@
 # SPDX-License-Identifier: LicenseRef-CSSL-1.0
 
-SUPPORTED_DISTRO="Ubuntu 20.04,22.04, RHEL 9.x, UBI 9.x, Rocky-Linux 9.x"
-if [ ! -f /etc/os-release ]; then
-  echo_fatal "No /etc/os-release file found. You're likely on an unsupported distro."
-fi
-OS_DISTRO=$(grep "^ID=" /etc/os-release | sed "s/ID=//" | sed "s/\"//g")
-OS_RELEASE=$(grep "^VERSION_ID=" /etc/os-release | sed "s/VERSION_ID=//" | sed "s/\"//g")
-case "$OS_DISTRO" in
-  fedora) OS_BASEDISTRO="fedora"; INSTALLER="dnf"; CMAKE="cmake" ;;
-  rocky)  OS_BASEDISTRO="fedora"; INSTALLER="dnf"; CMAKE="cmake" ;;
-  rhel)   OS_BASEDISTRO="fedora"; INSTALLER="dnf"; CMAKE="cmake" ;;
-  debian) OS_BASEDISTRO="debian"; INSTALLER="apt-get"; CMAKE="cmake" ;;
-  ubuntu) OS_BASEDISTRO="debian"; INSTALLER="apt-get"; CMAKE="cmake" ;;
-esac
+# -------------------------------------------------------------------------------
+# Shell helpers shared by the OAI CN5G build scripts: colored logging,
+# distribution detection, package installation and compilation wrappers.
+# Sourced, never executed.
+# -------------------------------------------------------------------------------
 
-IS_CONTAINER=`egrep -c "docker|kubepods|podman|buildah|libpod" /proc/self/cgroup || true`
-IS_DOCKERBUILD=${IS_DOCKERFILE:-0}
+# -------------------------------------------------------------------------------
+# Colored logging.
+# -------------------------------------------------------------------------------
 
-if [ $IS_CONTAINER -eq 0 ] && [ $IS_DOCKERBUILD -eq 0 ]
-then
-  SUDO='sudo -S -E'
-else
-  SUDO=''
-  IS_CONTAINER=1
-fi
-
-###############################
-## echo and  family
-###############################
-black='\E[30m'
 red='\E[31m'
 green='\E[32m'
 yellow='\E[33m'
 blue='\E[1;34m'
-magenta='\E[35m'
-cyan='\E[36m'
-white='\E[37m'
 reset_color='\E[00m'
 COLORIZE=1
 
-#-------------------------------------------------------------------------------
-cecho()  {
-    # Color-echo
-    # arg1 = message
-    # arg2 = color
-    local default_msg="No Message."
-    message=${1:-$default_msg}
-    color=${2:-$green}
-    [ "$COLORIZE" = "1" ] && message="$color$message$reset_color"
-    echo -e "$message"
-    return
+# arg1 is the message
+# arg2 is the color (defaults to green)
+cecho() {
+  local message=${1:-"No Message."}
+  local color=${2:-$green}
+  [ "$COLORIZE" = "1" ] && message="$color$message$reset_color"
+  echo -e "$message"
 }
 
 echo_error()   { cecho "$*" $red          ;}
@@ -58,261 +32,161 @@ echo_warning() { cecho "$*" $yellow       ;}
 echo_success() { cecho "$*" $green        ;}
 echo_info()    { cecho "$*" $blue         ;}
 
-#-------------------------------------------------------------------------------
-# From https://stackoverflow.com/questions/4023830/how-to-compare-two-strings-in-dot-separated-version-format-in-bash
-# arg1 is a dotted (or not) version number (ex 4.10.6.56-ubunutu)
-# arg2 is a dotted (or not) version number (ex 4.10.6.56-ubunutu)
-# return 0 if $1 lower or equal $2, else 1
-version_le() {
-  [  "$1" = "`echo -e "$1\n$2" | sort -V | head -n1`" ]
-}
+# -------------------------------------------------------------------------------
+# Distribution and host detection. Runs at source time and sets the variables
+# the per-dependency helpers rely on: INSTALLER, OS_BASEDISTRO, CMAKE and SUDO.
+# -------------------------------------------------------------------------------
 
-# From https://stackoverflow.com/questions/4023830/how-to-compare-two-strings-in-dot-separated-version-format-in-bash
-version_lt() {
-  [ "$1" = "$2" ] && return 1 || version_le $1 $2
-}
+SUPPORTED_DISTRO="Ubuntu 24.04, RHEL 9.x, UBI 9.x, Rocky-Linux 9.x"
+if [ ! -f /etc/os-release ]; then
+  echo_fatal "No /etc/os-release file found. You're likely on an unsupported distro."
+fi
+OS_DISTRO=$(grep "^ID=" /etc/os-release | sed "s/ID=//" | sed "s/\"//g")
+OS_RELEASE=$(grep "^VERSION_ID=" /etc/os-release | sed "s/VERSION_ID=//" | sed "s/\"//g")
+CMAKE="cmake"
+case "$OS_DISTRO" in
+  fedora|rocky|rhel) OS_BASEDISTRO="fedora"; INSTALLER="dnf" ;;
+  debian|ubuntu)     OS_BASEDISTRO="debian"; INSTALLER="apt-get" ;;
+esac
 
-# From https://stackoverflow.com/questions/4023830/how-to-compare-two-strings-in-dot-separated-version-format-in-bash
-version_ge() {
-  [  "$1" = "`echo -e "$1\n$2" | sort -V | tail -n1`" ]
-}
+IS_CONTAINER=`grep -E -c "docker|kubepods|podman|buildah|libpod" /proc/self/cgroup || true`
 
-# From https://stackoverflow.com/questions/4023830/how-to-compare-two-strings-in-dot-separated-version-format-in-bash
-version_gt() {
-  [ "$1" = "$2" ] && return 1 || version_ge $1 $2
-}
+# inside a container we already run as root, so sudo is neither needed nor present
+if [ $IS_CONTAINER -eq 0 ] && [ ${IS_DOCKERFILE:-0} -eq 0 ]
+then
+  SUDO='sudo -S -E'
+else
+  SUDO=''
+  IS_CONTAINER=1
+fi
 
-########################
-# distribution helpers #
-########################
-
-#-------------------------------------------------------------------------------
-# This function return a string to identify the distribution we are running
-# If we can't check the distribution, it returns "Unknown"
-# This function return always true as exit code by design
-# Examples:
-#   ubuntu20.04
-#   rhel8.8
+# echoes the running distribution, ex "ubuntu24.04", or "Unknown"
 get_distribution_release() {
-    if [[ ! -z "$OS_DISTRO$OS_RELEASE" ]]; then
-        echo -n "$OS_DISTRO$OS_RELEASE"
-    else
-        echo -n Unknown
-    fi
+  local release="$OS_DISTRO$OS_RELEASE"
+  echo -n "${release:-Unknown}"
 }
 
+# returns 0 if the running distribution is one of $SUPPORTED_DISTRO
 check_supported_distribution() {
-    local distribution=$(get_distribution_release)
-    case "$distribution" in
-        "ubuntu20.04") return 0 ;;
-        "ubuntu22.04") return 0 ;;
-        "rhel9.3")     return 0 ;;
-        "rhel9.4")     return 0 ;;
-        "rhel9.5")     return 0 ;;
-        "rhel9.6")     return 0 ;;
-        "rhel9.7")     return 0 ;;
-        "rhel9.8")     return 0 ;;
-        "rocky9.3")    return 0 ;;
-        "rocky9.4")    return 0 ;;
-        "rocky9.5")    return 0 ;;
-        "rocky9.6")    return 0 ;;
-    esac
-    return 1
+  case "$(get_distribution_release)" in
+    ubuntu24.04|rhel9.[3-8]|rocky9.[3-8]) return 0 ;;
+  esac
+  return 1
 }
 
-###########################
-# Cleaners
-###########################
-
-#-------------------------------------------------------------------------------
-clean_kernel() {
-  $SUDO modprobe ip_tables
-  $SUDO modprobe x_tables
-  $SUDO iptables -P INPUT ACCEPT
-  $SUDO iptables -F INPUT
-  $SUDO iptables -P OUTPUT ACCEPT
-  $SUDO iptables -F OUTPUT
-  $SUDO iptables -P FORWARD ACCEPT
-  $SUDO iptables -F FORWARD
-  $SUDO iptables -t nat -F
-  $SUDO iptables -t mangle -F
-  $SUDO iptables -t filter -F
-  $SUDO iptables -t raw -F
-  echo_info "Flushed iptables"
-}
-
-
-#-------------------------------------------------------------------------------
+# skipped in a container, where the sysctl is usually not writable
 disable_ipv6() {
   if [ $IS_CONTAINER -eq 0 ]
   then
-      $SUDO sysctl -w net.ipv6.conf.all.disable_ipv6=1
+    $SUDO sysctl -w net.ipv6.conf.all.disable_ipv6=1
   fi
 }
 
+# -------------------------------------------------------------------------------
+# Shell utilities.
+# -------------------------------------------------------------------------------
 
-#-------------------------------------------------------------------------------
-# Compare two versions of software. Returns true if $version is greater than $req_version
-# arg1 = version
-# arg2 = req_version
-#
-function version_gt() {
-  test "$(printf '%s\n' "$@" | sort -V | head -n 1)" != "$1";
+# arg1 is the list, ex "item1 item2 ..."
+# arg2 is the item to look for
+list_include_item() {
+  [[ "$1" =~ (^|[[:space:]])"$2"($|[[:space:]]) ]]
 }
 
+# -------------------------------------------------------------------------------
+# Compilation and unit test wrappers. Both log to $dlog, and compilations()
+# also passes $make_args to make; both are set by the calling build script.
+# -------------------------------------------------------------------------------
 
-###################################
-# Compilers
-###################################
-
-# From https://stackoverflow.com/a/20473191
-# test if a list include item
-# arg1 is list, ex "item1 item2 ..."
-# arg2 is item
-function list_include_item {
-  local list="$1"
-  local item="$2"
-  if [[ $list =~ (^|[[:space:]])"$item"($|[[:space:]]) ]] ; then
-    # yes, list include item
-    result=0
-  else
-    result=1
-  fi
-  return $result
-}
-
-# arg 1 Build directory OPENAIR_DIR/build/?/build
-# arg 2 Executable target name
-# arg 3 Executable name (no path)
-# arg 4 Verbose         (1 or 0)
+# arg1 is the build subdirectory, built in $OPENAIRCN_DIR/build/<arg1>/build
+# arg2 is the make target name, also used as the log file name
+# arg3 is the produced executable, absolute or relative to the build directory
+# arg4 is verbose (0 or 1)
 compilations() {
   echo_info "Compilation log for $3 is here: $dlog/$2.txt"
-  cd $OPENAIRCN_DIR/build/$1/build
+  cd $OPENAIRCN_DIR/build/$1/build || return 1
+  rm -f $3
   if [ "a$4" == "a1" ]; then
     set -o pipefail
-    {
-      rm -f $3
-      make $make_args $2
-    } |& tee $dlog/$2.txt
+    make $make_args $2 |& tee $dlog/$2.txt
   else
-    {
-      rm -f $3
-      make $make_args $2
-    } > $dlog/$2.txt 2>&1
+    make $make_args $2 > $dlog/$2.txt 2>&1
   fi
-  if [ $? == 0 -a -s $3 ] ; then
-     echo_success "$2 compiled"
-     return 0
-  else
-     echo_error "$2 compilation failed"
-     return 1
+  if [ $? -eq 0 ] && [ -s $3 ]; then
+    echo_success "$2 compiled"
+    return 0
   fi
+  echo_error "$2 compilation failed"
+  return 1
 }
 
-###################################
-# make test
-###################################
-
-# arg 1 Build directory OPENAIRCN_DIR/build/?/build
-# arg 2 Executable target name
-# arg 3 Executable name (no path)
-# arg 4 Verbose         (1 or 0)
+# arg1 is the build subdirectory, as for compilations()
+# arg2 is the log file name prefix
+# arg3 is ignored, callers pass it to keep the compilations() argument order
+# arg4 is verbose (0 or 1)
 make_test() {
   echo_success "unit tests start"
-  cd $OPENAIRCN_DIR/build/$1/build
+  cd $OPENAIRCN_DIR/build/$1/build || return 1
   if [ "a$4" == "a1" ]; then
-    {
-      make test ARGS="-V"
-    } | tee $dlog/$2_test.txt
+    make test ARGS="-V" | tee $dlog/$2_test.txt
   else
-    {
-      make test
-    } > $dlog/$2_test.txt 2>&1
+    make test > $dlog/$2_test.txt 2>&1
   fi
   echo_success "unit tests end"
 }
 
-#-------------------------------------------------------------------------------
-# arg1 is package name
-test_install_package() {
-  # usage: test_install_package package_name
- if [ $# -eq 1 ]; then
-   dpkg -s "$1" > /dev/null 2>&1 && {
-          echo "$1 is installed."
-      } || {
-      echo "$1 is not installed."
-      $SUDO apt-get install --force-yes $1
-    }
-  fi
-}
+# -------------------------------------------------------------------------------
+# Package management.
+# -------------------------------------------------------------------------------
 
-
-#-------------------------------------------------------------------------------
 update_package_db() {
-  if [ ! -f /tmp/no_more_update_package_db ]; then
-    $SUDO $INSTALLER update
-    [[ $? -ne 0 ]] && return $?
-    touch /tmp/no_more_update_package_db
-    [[ $? -ne 0 ]] && return $?
-  else
-    let elapsed_time=$(expr `date +%s` - `stat -c %Y /tmp/no_more_update_package_db`)
-    if [ $elapsed_time -gt 3600 ]; then
-      $SUDO $INSTALLER update
-      [[ $? -ne 0 ]] && return $?
-      touch /tmp/no_more_update_package_db
-      [[ $? -ne 0 ]] && return $?
-    fi
+  local stamp=/tmp/no_more_update_package_db
+
+  # the package database is refreshed at most once an hour
+  if [ -f $stamp ] && [ $(( $(date +%s) - $(stat -c %Y $stamp) )) -le 3600 ]; then
+    return 0
   fi
-  return 0
+
+  $SUDO $INSTALLER update || return $?
+  touch $stamp
 }
 
-#-------------------------------------------------------------------------------
+# on Enterprise Linuxes, ensure EPEL repos are installed
+# (provides: libidn2-devel, vconfig, iperf, phpMyAdmin, dkms, ...)
 check_enable_epel_repos() {
-  # on Enterprise Linuxes, ensure EPEL repos are installed
-  # (provides: libidn2-devel, vconfig, iperf, phpMyAdmin, dkms, ...)
-  EPEL_URL=${EPEL_URL:-"https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm"}
-  if [[ "$OS_DISTRO" == "rhel" ]] || [[ "$OS_DISTRO" == "centos" ]]; then
-    if rpm -q epel-release > /dev/null; then
-      echo "EPEL repos already present. Good."
-    else
-      echo "EPEL repos not present. Installing them."
-      idx=0
-      while [[ $idx -lt 4 ]]; do
-        wget --tries=4 --retry-connrefused --wait=8 \
-          --user-agent="Mozilla" \
-          "$EPEL_URL"
-        # Use RPM package from OAI EURECOM
-        if [[ $? -eq 0 ]] && file epel-release-latest-9.noarch.rpm | grep -q "RPM"; then
-          # Verify if it is a valid RPM
-          # (For example, epel-release-latest-9.noarch.rpm: RPM v3.0 bin noarch)
-          idx=10
-        else
-          if [[ -f epel-release-latest-9.noarch.rpm ]]; then
-            # If it downloads HTML File and not a valid RPM, for instance, retry
-            echo "Attempt $((idx+1)) failed: Downloaded $(file -b epel-release-latest-9.noarch.rpm)"
-            rm -f epel-release-latest-9.noarch.rpm
-          fi
-          idx=$(($idx+1))
-          sleep 1
-        fi
-      done
-      if [[ $idx -eq 4 ]]; then
-        echo "Error: Could not download the EPEL-9 RPM file"
-        exit 1
-      fi
-      $SUDO $INSTALLER install $OPTION epel-release-latest-9.noarch.rpm
-      rm -f epel-release-latest-9.noarch.rpm
-    fi
+  local rpm=epel-release-latest-9.noarch.rpm
+  EPEL_URL=${EPEL_URL:-"https://dl.fedoraproject.org/pub/epel/$rpm"}
+
+  [[ "$OS_DISTRO" == "rhel" || "$OS_DISTRO" == "centos" ]] || return 0
+  if rpm -q epel-release > /dev/null; then
+    echo "EPEL repos already present. Good."
+    return 0
   fi
+
+  echo "EPEL repos not present. Installing them."
+  local idx
+  for idx in 1 2 3 4; do
+    wget --tries=4 --retry-connrefused --wait=8 --user-agent="Mozilla" "$EPEL_URL" \
+      && file $rpm | grep -q "RPM" && break
+    # a download can yield an HTML error page instead of an RPM, retry in that case
+    echo "Attempt $idx failed: downloaded $(file -b $rpm 2>/dev/null)"
+    rm -f $rpm
+    sleep 1
+  done
+  if [ ! -f $rpm ]; then
+    echo "Error: Could not download the EPEL-9 RPM file"
+    exit 1
+  fi
+
+  $SUDO $INSTALLER install $OPTION $rpm
+  rm -f $rpm
 }
 
-################################
-# set_openair_env
-###############################
-#-------------------------------------------------------------------------------
-set_openair_env(){
-  script_path=$BASH_SOURCE
-  script_dir=$(dirname ${script_path})
-  root_dir=$(realpath ${script_dir}/../../..)
-  export OPENAIRCN_DIR=${root_dir}
+# -------------------------------------------------------------------------------
+# Build environment.
+# -------------------------------------------------------------------------------
+
+# this file lives in <root>/build/common-build/installation, so the repository
+# root is three levels up
+set_openair_env() {
+  export OPENAIRCN_DIR=$(realpath $(dirname $BASH_SOURCE)/../../..)
 }
