epel_fix: validate downloaded EPEL RPM content and update mirror
        - Retry if non-RPM file is downloaded
        - Switch EPEL download mirror to OAI EURECOM.

diff --git a/installation/build_helper b/installation/build_helper
--- a/installation/build_helper
+++ b/installation/build_helper
@@ -303,12 +303,20 @@ check_enable_epel_repos() {
       while [[ $idx -lt 4 ]]; do
         wget --tries=4 --retry-connrefused --wait=8 \
           --user-agent="Mozilla" \
-          https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
-        if [[ $? -ne 0 ]]; then
+          https://oai.eurecom.io/ci-package-mirrors/epel/epel-release-latest-9.noarch.rpm
+        # Use RPM package from OAI EURECOM
+        if [[ $? -eq 0 ]] && file epel-release-latest-9.noarch.rpm | grep -q "RPM"; then
+          # Verify if it is a valid RPM
+          # (For example, epel-release-latest-9.noarch.rpm: RPM v3.0 bin noarch)
+          idx=10
+        else
+          if [[ -f epel-release-latest-9.noarch.rpm ]]; then
+            # If it downloads HTML File and not a valid RPM, for instance, retry
+            echo "Attempt $((idx+1)) failed: Downloaded $(file -b epel-release-latest-9.noarch.rpm)"
+            rm -f epel-release-latest-9.noarch.rpm
+          fi
           idx=$(($idx+1))
           sleep 1
-        else
-          idx=10
         fi
       done
       if [[ $idx -eq 4 ]]; then
